[package]
name = "bestbank"
version = "0.1.0"
authors = ["jgrant"]
edition = "2018"

[dependencies]
t_bang = "0.1.2"
maplit = "1.0.1"
md5 = "0.6.1"
chrono = "0.4.6"
rocket = { version="0.4.0", features = ["private-cookies", "tls"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version="0.4.0"
disable-features=false
features=["json", "handlebars_templates"]
